### ISSUE TITLE
PhoneGap to Cordova

### ISSUE THREAD

**Issue by zxiu** [kjda/ReactJs-Phonegap#10]
I am a beginner to the Corss-platt Area. 
As i folllow the document by create app, i get error as bellow:
How could i fix it? is the sample pass the new Cordova?

$ gulp create
[09:22:39] Using gulpfile ~/CordovaProject/ReactJs-Phonegap/app/gulpfile.js
[09:22:39] Starting 'create'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[09:22:39] Starting 'clean-app'...
[09:22:39] Finished 'clean-app' after 14 ms
[09:22:39] Starting 'create-app'...
/bin/sh: phonegap: command not found
[09:22:39] 'create-app' errored after 30 ms
[09:22:39] Error in plugin 'gulp-shell'
Message:
    Command failed: /bin/sh -c phonegap create phonegap-app
/bin/sh: phonegap: command not found

Details:
    killed: false
    code: 127
    signal: null
    cmd: /bin/sh -c phonegap create phonegap-app
    stdout:
    stderr: /bin/sh: phonegap: command not found

[09:22:39] 'create' errored after 50 ms
[09:22:39] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp-cli/index.js:173:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp-cli/index.js:199:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/zxui/CordovaProject/ReactJs-Phonegap/app/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/zxui/CordovaProject/ReactJs-Phonegap/app/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/zxui/CordovaProject/ReactJs-Phonegap/app/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/zxui/CordovaProject/ReactJs-Phonegap/app/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/zxui/CordovaProject/ReactJs-Phonegap/app/node_modules/gulp-run-sequence/index.js:35:5)
    at Gulp.onError (/Users/zxui/CordovaProject/ReactJs-Phonegap/app/node_modules/gulp-run-sequence/index.js:41:4)
    at Gulp.emit (events.js:129:20)

**Comment by guerjon** [comment]
i  have the save problem!

**Comment by guerjon** [comment]
I solved, in build.configs.js you should change

org.apache.cordova.geolocation by https://github.com/apache/cordova-plugin-geolocation.git org.apache.cordova.statusbar  by https://github.com/apache/cordova-plugin-statusbar.git
 org.apache.cordova.splashscreen by https://github.com/apache/cordova-plugin-splashscreen.git

because gulp can't not make the fetch to the org.apachecordoba.*
